// src/frontend/components/CopyButton.vue
<template>
  <button class="btn btn-primary" @click="click" :disabled="disabled">
    copy
  </button>
</template>

<script>
import copyToClipboard from "../lib/copy-to-clipboard";

export default {
  props: ["text", "disabled"],

  methods: {
    click() {
      copyToClipboard(this.text);
    }
  }
};
</script>

// lib/components/CopyButton.jsx
import React from "react";
import copyToClipboard from "../copy-to-clipboard";

export default function CopyButton(_props) {
    const { text, ...props } = _props;
    return <button onClick={() => copyToClipboard(text)} {...props} />;
}

CopyButton.propTypes = {
    text: React.PropTypes.string.isRequired
};
